Fix: build.gradle 수정

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -30,11 +30,12 @@ jobs:
 
     - name: Set environment values
       run: |
-        touch .env
-        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
-        echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
-        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
-        ls
+        touch .env  # .env 파일 생성
+        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env || echo "Failed to set DATABASE_URL"
+        echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env || echo "Failed to set DATABASE_USERNAME"
+        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env || echo "Failed to set DATABASE_PASSWORD"
+        ls  # 현재 디렉토리의 파일 목록
+
     - name: Build with Gradle
       run: ./gradlew clean build -x test
   
